### ISSUE TITLE
Need to add support for other selectors not only className

### ISSUE THREAD

**Issue by rparsh** [ashrivas8/bootcamp#1]
https://github.com/ashrivas8/bootcamp/blob/d1e035a768597a5c0506f40dd735086f7f761eb7/w1-d2/razor.js#L8

Below cases should work
```js
$razor('#selector')
$razor('.selector')
$razor('h1')
```

**Comment by ashrivas8** [comment]
Added support for the other selectors: https://github.com/ashrivas8/bootcamp/commit/bb5ad9da14a4ecd7cbc4970844945b352c036a62
